language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
      secure: "eqfiC29oAviAghgxzauAWomRZ7dlTf0++SQ0bKSPYxRUwPAfUFHPnbSAiGBsXJUDXyj6gJSMflYBgVEVnnbfJa5LPnlW5cfo3pyDEqdlC/0hRrCnmgmc9BcEu4nGiK0NgGGDgp+Uz3tTi4Y+jyg9MWLk3AJv4nc0sXVYdXsmSyoBcSdaGNwR3Xg4571MxxVlJwa1lW1bXiPP3pfXzEcQR6cCjsI6JohBSf3+WaFUA3v5wwg6chpwtRBidudFGdY2AmxoP+5noraiNQiUGQEP+iROFjzueR+i3m6IA52HdKwW4wlih3nllzPMGRwF6/BB1HsI3GAdLjnBoVnM3hkIaIftRHV8aIcWEGcWEmNq3dLZEejQHveo7Ek/+UM7oPy2ILq6e4kVNJD9/v61yt0biBhF21NGW2J7ZnRc85HEW8N+RVQzfhNLwZFq5oqO0b4hB+kti3uXGKCScUku8JJXVwpbcy116nHbrZBfld/IIKYWFM59ydezL6wzhlUBq7hXBFW1/5sw8OIfPOScbIiThL1uYu6Ei4dVsTbzFn8tn4vPiE1EtNP0fVau+iGtkAyomvU8UwUbUUBvyNut+ByGg9gFs4pDeH0bib0r5b4zlAcilUMfbTDPa1pVEU60oy3Dbm9MCEKjJ2Rv5T0IZdIlnvrlLTuW8g9lvs66Hb0rGGU="

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"